### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by AmritPatel** [DiegoSSaenz/RetirementCaseStudy1#2]
- [x] This is an example (Diego please take the first action to make an _actual_ list).
- [x] Add savings
- [x] Add taxable investment account
- [ ] Add functionality to consider children
- [x] Add function with FAFSA calculation (Diego)
- [x] Add spending column
- [ ] Add spending based on an input fixed value
- [x] Add spending based on an input savings rate
- [ ] Add functionality to consider large spending events
- [ ] Think of other features to add (your turn Amrit)
- [ ] Measure performance difference of original script, script with mapply and script with mcapply (Amrit)
- [x] Add pension function
- [ ] Make more efficient over time (Diego)
